ktor:
    application:
        modules:
            - com.foodjournal.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 443
        port-external: 443
        address: "https://foodnotes.ru"
    fooddb:
        path: "mongodb://localhost:27017"
        dbname: "foodJournal"
    security:
        ssl: 
            keyStore: keystore.jks
            keyAlias: keystorefood
            keyStorePassword: $KEYSTORE_PASSWORD
            privateKeyPassword: $PRIVATEKEY_PASSWORD

        

    
