ktor:
    application:
        modules:
            - com.foodjournal.ApplicationKt.module
    deployment:
        port: 8080
    fooddb:
        path: "mongodb://localhost:27017"
        dbname: "foodJournal"
    security:
        sign: "dev-secret111111"
        encrypt: "dev-secret-encry"

    
