ktor:
    application:
        modules:
            - com.foodjournal.ApplicationKt.module
    deployment:
        port: 8080
    database:
        path: "mongodb://localhost:27017"
        dbname: "foodJournal"
    security:
        secret: "dev-secret"
        google-client-id: "google-secret"
    
